/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class MatchCreator extends javax.swing.JFrame {

    /**
     * Creates new form MatchCreator
     */
    
    public String team1;
    public String team2;
    public int t1;
    public int t2;
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/login","root","test123");
    
    public MatchCreator() throws SQLException {
        initComponents();
        setTitle("Match Creator");
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MatchCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String sql = "select * from team";
        try{
            PreparedStatement PST=conn.prepareStatement(sql);
            ResultSet RS=PST.executeQuery();
            while(RS.next()){
                Team1Combo.addItem(RS.getString("NAME"));
                Team2Combo.addItem(RS.getString("NAME"));
            }
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        CreateButton = new javax.swing.JButton();
        Team1Combo = new javax.swing.JComboBox<>();
        SeasonTextField = new javax.swing.JTextField();
        OverTextField = new javax.swing.JTextField();
        Team2Combo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1417, 944));

        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1417, 944));
        kGradientPanel1.setLayout(null);

        CreateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CreateButton.setText("CREATE");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(CreateButton);
        CreateButton.setBounds(1120, 420, 110, 23);

        kGradientPanel1.add(Team1Combo);
        Team1Combo.setBounds(830, 290, 140, 20);
        kGradientPanel1.add(SeasonTextField);
        SeasonTextField.setBounds(830, 540, 140, 30);
        kGradientPanel1.add(OverTextField);
        OverTextField.setBounds(830, 470, 140, 30);

        Team2Combo.setToolTipText("");
        kGradientPanel1.add(Team2Combo);
        Team2Combo.setBounds(830, 380, 140, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("SEASON");
        jLabel5.setOpaque(true);
        kGradientPanel1.add(jLabel5);
        jLabel5.setBounds(690, 540, 70, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("OVERS");
        jLabel3.setOpaque(true);
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(690, 470, 70, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("TEAM 2");
        jLabel4.setOpaque(true);
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(690, 380, 70, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("TEAM 1");
        jLabel2.setOpaque(true);
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(690, 290, 70, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/Collection-pg-Cricket-1.jpg"))); // NOI18N
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1417, 944);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1275, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        team1 = Team1Combo.getSelectedItem().toString();
        team2 = Team2Combo.getSelectedItem().toString();
        
        if(team1.equals(team2)){
            JOptionPane.showMessageDialog(null,"Cannot have the same teams playing each other!", "ERROR!",JOptionPane.ERROR_MESSAGE);
        }else{
         
            JOptionPane.showMessageDialog(null, "You Have Done It!", "SUCCESS!!" , JOptionPane.INFORMATION_MESSAGE);
            try {
                addToDatabase();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(MatchCreator.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_CreateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatchCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatchCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatchCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatchCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MatchCreator().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MatchCreator.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateButton;
    private javax.swing.JTextField OverTextField;
    private javax.swing.JTextField SeasonTextField;
    private javax.swing.JComboBox<String> Team1Combo;
    private javax.swing.JComboBox<String> Team2Combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables

    private void RetrieveID(String name1, String name2) throws ClassNotFoundException, SQLException{
        
        String sql = "select * from team where Name='"+name1+"'"; //'"+eid+"'"
        PreparedStatement PST=conn.prepareStatement(sql);
        ResultSet RS=PST.executeQuery();
        while(RS.next()){
            t1=RS.getInt(1);  
        }
        
        sql = "select * from team where Name='"+name2+"'"; //'"+eid+"'"
        PST=conn.prepareStatement(sql);
        RS=PST.executeQuery();
        while(RS.next()){
            t2=RS.getInt(1);  
        }
    }
    
    
    private void addToDatabase() throws ClassNotFoundException, SQLException {
        
        RetrieveID(team1,team2); //TID pailam
        String sql = "insert into `match` (TID_1,TID_2,Overs,Season) values (?,?,?,?)";
        PreparedStatement PST = conn.prepareStatement(sql); 
        
        int over = Integer.parseInt(OverTextField.getText());
        int season = Integer.parseInt(SeasonTextField.getText());
        
        
        PST.setInt(1,t1);
        PST.setInt(2,t2);
        PST.setInt(3,over);
        PST.setInt(4,season);
        PST.executeUpdate();
        
        conn.close();
        dispose();
        
        MatchPlayers mp;
        mp = new MatchPlayers(team1,team2);
        mp.setVisible(true);
        
    }
    
}
