/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cricket.scoreboard;

/**
 *
 * @author ASUS
 */
public class scoreboard extends javax.swing.JFrame {

    /**
     * Creates new form scoreboard
     */
    public scoreboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        runsfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        wicketsfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BATSMAN1 = new javax.swing.JLabel();
        BATSMAN2 = new javax.swing.JLabel();
        BATSMAN1RUN = new javax.swing.JTextField();
        BATSMAN2RUN = new javax.swing.JTextField();
        EXTRAS = new javax.swing.JLabel();
        OVERS = new javax.swing.JLabel();
        EXRUN = new javax.swing.JTextField();
        OV = new javax.swing.JTextField();
        PT = new javax.swing.JLabel();
        PRUN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        R2 = new javax.swing.JButton();
        R1 = new javax.swing.JButton();
        R5 = new javax.swing.JButton();
        R3 = new javax.swing.JButton();
        R6 = new javax.swing.JButton();
        R4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        R7 = new javax.swing.JButton();
        R8 = new javax.swing.JButton();
        R9 = new javax.swing.JButton();
        R10 = new javax.swing.JButton();
        R11 = new javax.swing.JButton();
        R12 = new javax.swing.JButton();
        R13 = new javax.swing.JButton();
        R14 = new javax.swing.JButton();
        R15 = new javax.swing.JButton();
        R16 = new javax.swing.JButton();
        R17 = new javax.swing.JButton();
        R18 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        R19 = new javax.swing.JButton();
        R20 = new javax.swing.JButton();
        R21 = new javax.swing.JButton();
        R22 = new javax.swing.JButton();
        R23 = new javax.swing.JButton();
        R24 = new javax.swing.JButton();
        R25 = new javax.swing.JButton();
        R26 = new javax.swing.JButton();
        R27 = new javax.swing.JButton();
        R28 = new javax.swing.JButton();
        R29 = new javax.swing.JButton();
        R30 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        runsfield.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("for");

        wicketsfield.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("CSE");

        BATSMAN1.setBackground(new java.awt.Color(0, 0, 0));
        BATSMAN1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        BATSMAN1.setForeground(new java.awt.Color(255, 255, 0));
        BATSMAN1.setText("BATSMEN 1");

        BATSMAN2.setBackground(new java.awt.Color(0, 0, 0));
        BATSMAN2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        BATSMAN2.setForeground(new java.awt.Color(255, 255, 0));
        BATSMAN2.setText("BATSMEN 2");

        BATSMAN1RUN.setBackground(new java.awt.Color(0, 0, 0));

        BATSMAN2RUN.setBackground(new java.awt.Color(0, 0, 0));

        EXTRAS.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        EXTRAS.setForeground(new java.awt.Color(255, 255, 0));
        EXTRAS.setText("EXTRAS");

        OVERS.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        OVERS.setForeground(new java.awt.Color(255, 255, 0));
        OVERS.setText("OVERS");

        EXRUN.setBackground(new java.awt.Color(0, 0, 0));
        EXRUN.setText("jTextField1");

        OV.setBackground(new java.awt.Color(0, 0, 0));
        OV.setText("jTextField2");

        PT.setBackground(new java.awt.Color(0, 0, 0));
        PT.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        PT.setForeground(new java.awt.Color(255, 255, 0));
        PT.setText("PARTNERSHIP");

        PRUN.setBackground(new java.awt.Color(0, 0, 0));
        PRUN.setText("jTextField1");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("RUN RATE");

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("BOWLER");

        jLabel5.setText("jLabel5");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("M");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("O");

        jLabel11.setText("jLabel11");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("R");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("W");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(PT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BATSMAN1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BATSMAN2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BATSMAN1RUN)
                                    .addComponent(BATSMAN2RUN)
                                    .addComponent(PRUN, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(jTextField1))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EXTRAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(OVERS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EXRUN, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(OV)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(120, 120, 120)
                                                .addComponent(jLabel9)
                                                .addGap(83, 83, 83))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23)))
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)))
                                .addGap(73, 73, 73)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(runsfield, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wicketsfield, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(runsfield)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(wicketsfield))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EXTRAS, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(BATSMAN1RUN)
                    .addComponent(BATSMAN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EXRUN))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BATSMAN2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BATSMAN2RUN)
                    .addComponent(OVERS, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(OV))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PT, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(PRUN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(53, 53, 53)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 857));

        R2.setText("2");
        getContentPane().add(R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1266, 22, 60, 37));

        R1.setText("1");
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });
        getContentPane().add(R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 22, 69, 37));

        R5.setText("5");
        getContentPane().add(R5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1266, 77, 60, 37));

        R3.setText("3");
        R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3ActionPerformed(evt);
            }
        });
        getContentPane().add(R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1353, 22, 57, 37));

        R6.setText("6");
        getContentPane().add(R6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1353, 77, 57, 37));

        R4.setText("4");
        getContentPane().add(R4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 77, 69, 37));

        jLabel14.setText("RUNS");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 60, 88, 31));

        jLabel15.setText("NO BALLS");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 199, -1, 28));

        R7.setText("5");
        getContentPane().add(R7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1266, 212, 60, 37));

        R8.setText("3");
        R8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R8ActionPerformed(evt);
            }
        });
        getContentPane().add(R8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1353, 157, 57, 37));

        R9.setText("6");
        getContentPane().add(R9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1353, 212, 57, 37));

        R10.setText("4");
        getContentPane().add(R10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 212, 69, 37));

        R11.setText("2");
        getContentPane().add(R11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1266, 157, 60, 37));

        R12.setText("1");
        getContentPane().add(R12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 157, 69, 37));

        R13.setText("5");
        getContentPane().add(R13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1266, 416, 60, 37));

        R14.setText("3");
        R14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R14ActionPerformed(evt);
            }
        });
        getContentPane().add(R14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1353, 358, 57, 37));

        R15.setText("6");
        getContentPane().add(R15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1353, 416, 57, 37));

        R16.setText("4");
        getContentPane().add(R16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 416, 69, 37));

        R17.setText("2");
        getContentPane().add(R17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1266, 358, 60, 37));

        R18.setText("1");
        getContentPane().add(R18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 358, 69, 37));

        jLabel16.setText("WIDES");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 416, -1, 28));

        R19.setText("5");
        getContentPane().add(R19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1266, 561, 60, 37));

        R20.setText("3");
        R20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R20ActionPerformed(evt);
            }
        });
        getContentPane().add(R20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1353, 503, 57, 37));

        R21.setText("6");
        getContentPane().add(R21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1353, 561, 57, 37));

        R22.setText("4");
        getContentPane().add(R22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 561, 69, 37));

        R23.setText("2");
        getContentPane().add(R23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1266, 503, 60, 37));

        R24.setText("1");
        getContentPane().add(R24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 503, 69, 37));

        R25.setText("5");
        getContentPane().add(R25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1266, 740, 60, 37));

        R26.setText("3");
        R26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R26ActionPerformed(evt);
            }
        });
        getContentPane().add(R26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1353, 682, 57, 37));

        R27.setText("6");
        getContentPane().add(R27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1353, 740, 57, 37));

        R28.setText("4");
        getContentPane().add(R28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 740, 69, 37));

        R29.setText("2");
        getContentPane().add(R29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1266, 682, 60, 37));

        R30.setText("1");
        getContentPane().add(R30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 682, 69, 37));

        jLabel17.setText("BYES");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 542, -1, 33));

        jLabel18.setText("LEG BYES");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1044, 716, -1, -1));

        jButton1.setText("WICKET");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1527, 24, 177, 55));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1459, 13, 50, 800));

        jButton2.setText("RETIRED");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1527, 146, 168, 52));

        jButton3.setText("SWAP BATSMAN");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1527, 270, 168, 58));

        jButton4.setText("SWAP BOWLER");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1527, 402, 168, 64));

        jButton5.setText("END OVER");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1527, 543, 168, 66));

        jButton6.setText("END INNINGS");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1527, 663, 168, 62));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 830, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R3ActionPerformed

    private void R8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R8ActionPerformed

    private void R14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R14ActionPerformed

    private void R20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R20ActionPerformed

    private void R26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R26ActionPerformed

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scoreboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BATSMAN1;
    private javax.swing.JTextField BATSMAN1RUN;
    private javax.swing.JLabel BATSMAN2;
    private javax.swing.JTextField BATSMAN2RUN;
    private javax.swing.JTextField EXRUN;
    private javax.swing.JLabel EXTRAS;
    private javax.swing.JTextField OV;
    private javax.swing.JLabel OVERS;
    private javax.swing.JTextField PRUN;
    private javax.swing.JLabel PT;
    private javax.swing.JButton R1;
    private javax.swing.JButton R10;
    private javax.swing.JButton R11;
    private javax.swing.JButton R12;
    private javax.swing.JButton R13;
    private javax.swing.JButton R14;
    private javax.swing.JButton R15;
    private javax.swing.JButton R16;
    private javax.swing.JButton R17;
    private javax.swing.JButton R18;
    private javax.swing.JButton R19;
    private javax.swing.JButton R2;
    private javax.swing.JButton R20;
    private javax.swing.JButton R21;
    private javax.swing.JButton R22;
    private javax.swing.JButton R23;
    private javax.swing.JButton R24;
    private javax.swing.JButton R25;
    private javax.swing.JButton R26;
    private javax.swing.JButton R27;
    private javax.swing.JButton R28;
    private javax.swing.JButton R29;
    private javax.swing.JButton R3;
    private javax.swing.JButton R30;
    private javax.swing.JButton R4;
    private javax.swing.JButton R5;
    private javax.swing.JButton R6;
    private javax.swing.JButton R7;
    private javax.swing.JButton R8;
    private javax.swing.JButton R9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField runsfield;
    private javax.swing.JTextField wicketsfield;
    // End of variables declaration//GEN-END:variables
}
