/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class OfficialData extends javax.swing.JFrame {

    /**
     * Creates new form OfficialData
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/login","root","test123");
    private int MID;
    
    public OfficialData() throws ClassNotFoundException, SQLException {
        initComponents();
        setTitle("Officials Data");
    }
    
    public OfficialData(int mid) throws ClassNotFoundException, SQLException {
        initComponents();
        setTitle("Officials Data");
        MID = mid;
        Class.forName("com.mysql.cj.jdbc.Driver");
        
        fillCombo();
    }


    
    
    
    
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateButton = new javax.swing.JButton();
        TossCombo = new javax.swing.JComboBox<>();
        ScorerText = new javax.swing.JTextField();
        UmpTwoText = new javax.swing.JTextField();
        UmpOneText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(612, 306));
        getContentPane().setLayout(null);

        CreateButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CreateButton.setText("Create Scorecard");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CreateButton);
        CreateButton.setBounds(300, 230, 150, 25);

        TossCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Team" }));
        getContentPane().add(TossCombo);
        TossCombo.setBounds(380, 180, 110, 20);
        getContentPane().add(ScorerText);
        ScorerText.setBounds(380, 140, 90, 22);
        getContentPane().add(UmpTwoText);
        UmpTwoText.setBounds(380, 110, 90, 22);
        getContentPane().add(UmpOneText);
        UmpOneText.setBounds(380, 80, 90, 22);

        jLabel5.setBackground(new java.awt.Color(204, 204, 240));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Toss Won By:");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 180, 87, 17);

        jLabel4.setBackground(new java.awt.Color(204, 204, 240));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("      Scorer:");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 140, 90, 20);

        jLabel3.setBackground(new java.awt.Color(204, 204, 240));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("    Umpire 2:");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 110, 90, 17);

        jLabel2.setBackground(new java.awt.Color(204, 204, 240));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("    Umpire 1:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 80, 90, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/istockphoto-639604868-612x612.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        
        String u1 = UmpOneText.getText();
        String u2 = UmpTwoText.getText();
        String u3 = ScorerText.getText();
        String s = TossCombo.getSelectedItem().toString();
        
        String sql = "update `match` set UMPIRE_1 = '"+u1+"' , UMPIRE_2 = '"+u2+"' , Scorer = '"+u3+"' , TOSS_CHOICE = '"+s+"' where  MID = '"+MID+"'";
        PreparedStatement PST;
        
        try {
            PST = conn.prepareStatement(sql);
            PST.executeUpdate();
            
            conn.close();
            JOptionPane.showMessageDialog(null, "Scorecard will be created soon! :p", "SUCCESS!!" , JOptionPane.INFORMATION_MESSAGE);
            dispose();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(OfficialData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CreateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfficialData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfficialData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfficialData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfficialData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new OfficialData().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(OfficialData.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateButton;
    private javax.swing.JTextField ScorerText;
    private javax.swing.JComboBox<String> TossCombo;
    private javax.swing.JTextField UmpOneText;
    private javax.swing.JTextField UmpTwoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    private void fillCombo() throws SQLException {
        
        String sql = "select * from `match` order by MID DESC LIMIT 1";
        PreparedStatement PST;
        ResultSet RS;
        
        PST = conn.prepareStatement(sql);
        RS  = PST.executeQuery();
        
        int t1=-1;
        int t2=-1;
        
        while(RS.next()){
            t1 = RS.getInt(2);
            t2 = RS.getInt(3);
        }
        
        sql = "select * from team where TID = '"+t1+"'";
        PST = conn.prepareStatement(sql);
        RS = PST.executeQuery();
        
        while(RS.next()){
            TossCombo.addItem(RS.getString("NAME"));
        }
        
        sql = "select * from team where TID = '"+t2+"'";
        PST = conn.prepareStatement(sql);
        RS = PST.executeQuery();
        
        while(RS.next()){
            TossCombo.addItem(RS.getString("NAME"));
        }
        
    }
}
